//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string Yourname { get; set; }
        public string Yourlogin { get; set; }
        public string YourPhoneNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Messages { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
