//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingLicenseIssueApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrivingLicenseIssueApp.TextUI", typeof(TextUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. сведения.
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес сервера.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные камеры.
        /// </summary>
        public static string AvailableCameras {
            get {
                return ResourceManager.GetString("AvailableCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать снимок.
        /// </summary>
        public static string CapturePhoto {
            get {
                return ResourceManager.GetString("CapturePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить подпись.
        /// </summary>
        public static string CaptureSignature {
            get {
                return ResourceManager.GetString("CaptureSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рег. номер ВУ.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрезать.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно сохранены.
        /// </summary>
        public static string DataSuccessfullySaved {
            get {
                return ResourceManager.GetString("DataSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные переданы на печать.
        /// </summary>
        public static string DataTransferredToPrint {
            get {
                return ResourceManager.GetString("DataTransferredToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действителен до.
        /// </summary>
        public static string DateOfExpiry {
            get {
                return ResourceManager.GetString("DateOfExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        public static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовление водительских удостоверений.
        /// </summary>
        public static string DLP {
            get {
                return ResourceManager.GetString("DLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фокус -.
        /// </summary>
        public static string FocusFar {
            get {
                return ResourceManager.GetString("FocusFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фокус +.
        /// </summary>
        public static string FocusNear {
            get {
                return ResourceManager.GetString("FocusNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_PRINT.
        /// </summary>
        public static string InPrint {
            get {
                return ResourceManager.GetString("InPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_WAIT.
        /// </summary>
        public static string InWait {
            get {
                return ResourceManager.GetString("InWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В печати.
        /// </summary>
        public static string IsSentToPrint {
            get {
                return ResourceManager.GetString("IsSentToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реестр водительских удостоверений.
        /// </summary>
        public static string ListDL {
            get {
                return ResourceManager.GetString("ListDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспорт.
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПИНФЛ.
        /// </summary>
        public static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место выдачи.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место жительства.
        /// </summary>
        public static string PlaceOfResidence {
            get {
                return ResourceManager.GetString("PlaceOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя принтера.
        /// </summary>
        public static string PrinterName {
            get {
                return ResourceManager.GetString("PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба печати запущена.
        /// </summary>
        public static string PrintServiceIsStarted {
            get {
                return ResourceManager.GetString("PrintServiceIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба печати успешно запущена.
        /// </summary>
        public static string PrintServiceSuccessfullyStarted {
            get {
                return ResourceManager.GetString("PrintServiceSuccessfullyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линия производства.
        /// </summary>
        public static string ProductionLine {
            get {
                return ResourceManager.GetString("ProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLISHED.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регионы.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация водительского удостоверения.
        /// </summary>
        public static string RegistrationNewDL {
            get {
                return ResourceManager.GetString("RegistrationNewDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных.
        /// </summary>
        public static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение данных.
        /// </summary>
        public static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить службу печати.
        /// </summary>
        public static string StartPrintService {
            get {
                return ResourceManager.GetString("StartPrintService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сфотографировать.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
