//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TizimNuuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> type { get; set; }
        public string FIO { get; set; }
        public string PhoneNumber { get; set; }
        public string Info { get; set; }
        public string lg { get; set; }
        public string pass { get; set; }
    
        public virtual TypePerson TypePerson { get; set; }
    }
}
