//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TizimNuuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTimeTableList
    {
        public int Id { get; set; }
        public string NameEduCourse { get; set; }
        public Nullable<int> WorksType { get; set; }
        public string Students { get; set; }
        public string Teachers { get; set; }
    
        public virtual WorksTypee WorksTypee { get; set; }
    }
}
