//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TizimNuuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class EduCoursesList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Teachers_Name { get; set; }
        public string Students_Name { get; set; }
        public string WorksList { get; set; }
        public string WorksNumber { get; set; }
        public Nullable<int> WorksType { get; set; }
        public Nullable<decimal> Ball { get; set; }
    
        public virtual WorksTypee WorksTypee { get; set; }
    }
}
