//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TizimNuuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationClientsUZMU
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Photo { get; set; }
        public Nullable<int> TypePerson { get; set; }
    
        public virtual TypePerson TypePerson1 { get; set; }
    }
}
