//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TizimNuuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersUZMU
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public string Direction { get; set; }
        public string Pulpit { get; set; }
        public string Photo { get; set; }
        public string Info { get; set; }
        public string PhoneNumber { get; set; }
    }
}
