//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintServiceApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintServiceApp.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Card encoding error.
        /// </summary>
        internal static string CardEncodingError {
            get {
                return ResourceManager.GetString("CardEncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_PRINT.
        /// </summary>
        internal static string InPrint {
            get {
                return ResourceManager.GetString("InPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_WAIT.
        /// </summary>
        internal static string InWait {
            get {
                return ResourceManager.GetString("InWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Job {1} state changed: {2}.
        /// </summary>
        internal static string JobStateChanged {
            get {
                return ResourceManager.GetString("JobStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........................
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} print jobs loaded.
        /// </summary>
        internal static string LoadPrintJobs {
            get {
                return ResourceManager.GetString("LoadPrintJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран принтер.
        /// </summary>
        internal static string NoPrinterSelected {
            get {
                return ResourceManager.GetString("NoPrinterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINTED.
        /// </summary>
        internal static string Printed {
            get {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Printer state: {1}.
        /// </summary>
        internal static string PrinterState {
            get {
                return ResourceManager.GetString("PrinterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print service.
        /// </summary>
        internal static string PrintService {
            get {
                return ResourceManager.GetString("PrintService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Print service started..
        /// </summary>
        internal static string PrintServiceStarted {
            get {
                return ResourceManager.GetString("PrintServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Print service stoped..
        /// </summary>
        internal static string PrintServiceStoped {
            get {
                return ResourceManager.GetString("PrintServiceStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLISHED.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Unable to set printer position: {1}.
        /// </summary>
        internal static string SetPrinterPositionError {
            get {
                return ResourceManager.GetString("SetPrinterPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Start print job: {1}.
        /// </summary>
        internal static string StartPrintJob {
            get {
                return ResourceManager.GetString("StartPrintJob", resourceCulture);
            }
        }
    }
}
