//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleLicenseIssueApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VehicleLicenseIssueApp.TextUI", typeof(TextUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. сведения.
        /// </summary>
        internal static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить Поиск.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масса без нагрузки.
        /// </summary>
        internal static string CurbWeight {
            get {
                return ResourceManager.GetString("CurbWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий Автомобиль.
        /// </summary>
        internal static string CurrentVehicle {
            get {
                return ResourceManager.GetString("CurrentVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно сохранены.
        /// </summary>
        internal static string DataSuccessfullySaved {
            get {
                return ResourceManager.GetString("DataSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные переданы на печать.
        /// </summary>
        internal static string DataTransferredToPrint {
            get {
                return ResourceManager.GetString("DataTransferredToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата истечение.
        /// </summary>
        internal static string DateOfExpire {
            get {
                return ResourceManager.GetString("DateOfExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        internal static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер двигателя.
        /// </summary>
        internal static string EngineNumber {
            get {
                return ResourceManager.GetString("EngineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность двигателя.
        /// </summary>
        internal static string EnginePower {
            get {
                return ResourceManager.GetString("EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить.
        /// </summary>
        internal static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип горючего.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная масса.
        /// </summary>
        internal static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физические лица.
        /// </summary>
        internal static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН.
        /// </summary>
        internal static string Inn {
            get {
                return ResourceManager.GetString("Inn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В печати.
        /// </summary>
        internal static string IsSentToPrint {
            get {
                return ResourceManager.GetString("IsSentToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реестр свидетельств о регистрации автомототранспортного средства.
        /// </summary>
        internal static string ListVL {
            get {
                return ResourceManager.GetString("ListVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка / Модель.
        /// </summary>
        internal static string MakeModel {
            get {
                return ResourceManager.GetString("MakeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый Автомобиль.
        /// </summary>
        internal static string NewVehicle {
            get {
                return ResourceManager.GetString("NewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество сидячих мест вместе с водителем.
        /// </summary>
        internal static string NumberOfSeats {
            get {
                return ResourceManager.GetString("NumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество стоячих мест.
        /// </summary>
        internal static string NumberOfStandees {
            get {
                return ResourceManager.GetString("NumberOfStandees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридические лица.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование организации.
        /// </summary>
        internal static string OrgName {
            get {
                return ResourceManager.GetString("OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспорт.
        /// </summary>
        internal static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПИНФЛ.
        /// </summary>
        internal static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        internal static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделение УБДД.
        /// </summary>
        internal static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация свидетельства о регистрации автомототранспортного средства.
        /// </summary>
        internal static string RegistrationNewVL {
            get {
                return ResourceManager.GetString("RegistrationNewVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переоформление.
        /// </summary>
        internal static string Restructuring {
            get {
                return ResourceManager.GetString("Restructuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных.
        /// </summary>
        internal static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особые отметки.
        /// </summary>
        internal static string SpecialMarks {
            get {
                return ResourceManager.GetString("SpecialMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гос номер.
        /// </summary>
        internal static string StateNumber {
            get {
                return ResourceManager.GetString("StateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гос. номерной знак.
        /// </summary>
        internal static string StateNumberPlate {
            get {
                return ResourceManager.GetString("StateNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспортное средство.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер кузова.
        /// </summary>
        internal static string VehicleIdentificationNumberKuzov {
            get {
                return ResourceManager.GetString("VehicleIdentificationNumberKuzov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер шасси.
        /// </summary>
        internal static string VehicleIdentificationNumberShassi {
            get {
                return ResourceManager.GetString("VehicleIdentificationNumberShassi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоискФорма.
        /// </summary>
        internal static string VLLegalSearchFrom {
            get {
                return ResourceManager.GetString("VLLegalSearchFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовление свидетельства о регистрации автомототранспортного средства.
        /// </summary>
        internal static string VLP {
            get {
                return ResourceManager.GetString("VLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год выпуска.
        /// </summary>
        internal static string YearOfManufacture {
            get {
                return ResourceManager.GetString("YearOfManufacture", resourceCulture);
            }
        }
    }
}
